USE Qmos;
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER' 
AND COLUMN_NAME = 'TX_FirstName')
ALTER TABLE [Security].[SM_USER] ADD TX_FirstName VARCHAR(20) NOT NULL DEFAULT '';
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER' 
AND COLUMN_NAME = 'TX_SecondName')
ALTER TABLE [Security].[SM_USER] ADD TX_SecondName VARCHAR(20) NULL;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER' 
AND COLUMN_NAME = 'TX_LastName')
ALTER TABLE [Security].[SM_USER] ADD TX_LastName VARCHAR(20) NOT NULL DEFAULT '';
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER' 
AND COLUMN_NAME = 'TX_SecondLastName')
ALTER TABLE [Security].[SM_USER] ADD TX_SecondLastName VARCHAR(20) NULL ;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER' 
AND COLUMN_NAME = 'TX_Phone')
ALTER TABLE [Security].[SM_USER] ADD TX_Phone VARCHAR(20) NULL;
GO

  IF  EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER' 
AND COLUMN_NAME = 'TX_FullName')
 ALTER TABLE [Qmos].[Security].[SM_USER] DROP COLUMN  TX_FullName
GO
IF  EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER' 
AND COLUMN_NAME = 'TX_UserName')
 ALTER TABLE [Qmos].[Security].[SM_USER] DROP COLUMN  TX_UserName
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER'  AND COLUMN_NAME = 'Id_PriceList')
    ALTER TABLE [Security].[SM_USER] ADD ID_PriceList INT NULL ;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_USER' 
AND COLUMN_NAME = 'DT_ValidDatePasswordRecoveryLink')
	ALTER TABLE [Qmos].[Security].[SM_USER] ADD [DT_ValidDatePasswordRecoveryLink] DATETIME NULL
GO

ALTER TABLE [Qmos].[Security].[SM_ROLE] ADD [BO_VisibleCliente] BIT DEFAULT 0
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Security' AND TABLE_NAME = 'SM_ROLE' AND COLUMN_NAME = 'BO_VisibleCliente')
BEGIN
	UPDATE [Qmos].[Security].[SM_ROLE] SET BO_VisibleCliente = 0
END